#
###################################
# Site wide configuration
####################################
#
title:       "Gallery In Shadow"
description: 'Hello and welcome.'
url:         # the base hostname & protocol for your site

#
###################################
# Jekyll configuration
####################################
#
markdown:          kramdown
highlighter:       pygments
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Shvier
  avatar: avatar.jpg
  job: "iOS & indie game Developer"
  bio: "Love it, do it."
  email: Shvier@sina.com
  disqus-shortname: ShvierBlog
  twitter: Shvier #username
  facebook: SherlockVier#username
  google:
    plus: #username
    analytics: UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Shvier #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
